version: '3.4'

services:
  
  redis:
    image: redis:alpine

  masa.scheduler.database:
     image: mcr.microsoft.com/mssql/server:2019-latest
     ports:
       - "14333:1433"
     environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y

  masa.scheduler.web.admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Develop
      - ASPNETCORE_URLS=http://+:80 #;https://+:443 
    ports:
      - "19600:80"
      - "19610:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - masa.scheduler.service.server

  masa.scheduler.service.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Develop
      - ASPNETCORE_URLS=http://+:80 #;https://+:443
      - DAPR_HTTP_PORT=3600
      - DAPR_GRPC_PORT=51000
    ports:
      - "19601:80"
      - "19611:443"
    depends_on:
      - masa.scheduler.database
      - redis
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  masa.scheduler.service.server.dapr:
    image: "daprio/daprd:1.5.1"
    command: ["./daprd",
      "-app-id", "masa-scheduler-server",
      "-app-port", "80",
      "-dapr-http-port", "3600",
      "-dapr-grpc-port", "51000",
      "-components-path", "/components"
      ]
    depends_on:
      - masa.scheduler.service.server
    volumes:
      - "./dapr/components/:/components"
    network_mode: "service:masa.scheduler.service.server"

  masa.scheduler.service.worker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Develop
      - ASPNETCORE_URLS=http://+:80 #;https://+:443
      - DAPR_HTTP_PORT=3601
      - DAPR_GRPC_PORT=51001
    ports:
      - "19602:80"
      - "19612:443"
    depends_on:
      - masa.scheduler.database
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  masa.scheduler.service.worker.dapr:
    image: "daprio/daprd:1.5.1"
    command: ["./daprd",
      "-app-id", "masa-scheduler-worker",
      "-app-port", "80",
      "-dapr-http-port", "3601",
      "-dapr-grpc-port", "51001",
      "-components-path", "/components"
      ]
    depends_on:
      - masa.scheduler.service.worker
    volumes:
      - "./dapr/components/:/components"
    network_mode: "service:masa.scheduler.service.worker"


  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50050:50000"