version: '3.4'

services:
  
  redis:
    image: redis:alpine

  masa.scheduler.database:
     image: mcr.microsoft.com/mssql/server:2019-latest
     ports:
       - "14333:1433"
     environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y

  masa.scheduler.web.admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "16000:80"
      - "16100:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - masa.scheduler.service.server

  masa.scheduler.service.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 #https://+:443;
    ports:
      - "16002:80"
      - "16102:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  masa.scheduler.service.server.dapr:
    image: "daprio/daprd:1.5.1"
    command: ["./daprd",
      "-app-id", "masa-scheduler-server",
      "-app-port", "80",
      "-components-path", "/components"
      ]
    depends_on:
      - masa.scheduler.service.server
    volumes:
      - "./dapr/components/:/components"
    network_mode: "service:masa.scheduler.service.server"

  masa.scheduler.service.worker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 #https://+:443;
    ports:
      - "16003:80"
      - "16103:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  masa.scheduler.service.worker.dapr:
    image: "daprio/daprd:1.5.1"
    command: ["./daprd",
      "-app-id", "masa-scheduler-worker",
      "-app-port", "80",
      "-components-path", "/components"
      ]
    depends_on:
      - masa.scheduler.service.worker
    volumes:
      - "./dapr/components/:/components"
    network_mode: "service:masa.scheduler.service.worker"


  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50050:50000"