name: Mirror to Giltab

on: [push, delete, create]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:                                            
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: '${{ secrets.GITLAB_ADDER }}/cicd/masa.scheduler.git'
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          PUSH_ALL_REFS: "false"
